#!/bin/bash
# Script de compilation et simulation pour test_wrapper_tb

# Nettoyer et créer les librairies
vdel -all -lib lib_rtl_top 2>/dev/null
vlib lib_rtl_top
vmap lib_rtl lib_rtl_top

vlog -sv ../../rtl/interface/*.sv -work lib_rtl_top

vlog -sv ../../rtl/top/wrappers/interface_wrapper.sv -work lib_rtl_top

vlog -sv ./common/*.sv -work lib_rtl_top

vlog -sv ./test_wrapper_tb.sv -work lib_rtl_top

vsim -voptargs=+acc lib_rtl_top.test_wrapper_tb
